#!/bin/sh

# Automatically generate .gitignore for home directory based on currently tracked files
# Author: Joshua Elliott

cd $HOME
GIT_TRACKED=`git ls-files`
#echo $GIT_TRACKED

rm $HOME/.gitignore
echo '*' > $HOME/.gitignore

for tracked in $GIT_TRACKED; do
  #echo "tracked: "$tracked
  echo "!"$tracked >> $HOME/.gitignore
done

echo "Creted new .gitignore"
